### ISSUE TITLE
CI reports success when constraints are not satisfiable

### ISSUE THREAD

**Issue by anton-trunov** [coq/opam-coq-archive#1083]
Please see https://github.com/coq/opam-coq-archive/pull/1082#issuecomment-567494993

**Comment by clarus** [comment]
I would say this is OK if a package is not compatible with a tested platform on the CI if the package says it explicitly. You mean that you expect the CI to check that a package is compatible with at least one platform?

**Comment by anton-trunov** [comment]
> You mean that you expect the CI to check that a package is compatible with at least one platform?

Yes, something like this. I would expect CI to check if the package under test is at all installable.

**Comment by anton-trunov** [comment]
I guess a package with a constraint like this one: `  "coq" {< "0.0"}` is not really useful, but CI currently does not check it.

**Comment by clarus** [comment]
Adding these checks: https://github.com/coq/opam-coq-archive/pull/1084

**Comment by clarus** [comment]
Should be done: 
![image](https://user-images.githubusercontent.com/316665/71186295-46110b80-227d-11ea-8262-204161795c00.png)

**Comment by anton-trunov** [comment]
Awesome!
