### ISSUE TITLE
coq.inria.fr/opam not synchronized

### ISSUE THREAD

**Issue by clarus** [coq/opam-coq-archive#11]
I just added the package `coq:coqide.8.5~beta2` one hour ago. Since it is not available on `coq.inria.fr/opam/released` yet whereas the update delay is of 10 minutes, I am afraid that the synchronization mechanism may be broken.

**Comment by mattam82** [comment]
Fixed now, the package does appear.

**Comment by thery** [comment]
On 17/08/15 09:26, Matthieu Sozeau wrote:
> Closed #11.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/coq/opam-coq-archive/issues/11#event-383924040
> 

Ça semble marcher, j'ai réussi à installer coqide avec opam install
coq:coqide

Merci

--
Laurent
