### ISSUE TITLE
coq-menhirlib removed sources

### ISSUE THREAD

**Issue by clarus** [coq/opam-coq-archive#1110]
Hi @fpottier and @jhjourdan ,

It seems to us that the following version of `coq-menhirlib` are not available anymore:
* https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-menhirlib/coq-menhirlib.20180530
* https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-menhirlib/coq-menhirlib.20180827
* https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-menhirlib/coq-menhirlib.20200121

The first two are removed due the removal of the https://gitlab.inria.fr/fpottier/coq-menhirlib repository. The last one is independent. Thus we are thinking to remove these packages if this is OK for you. Maybe the old archive could be hosted on the new repository, in case old projects depend on the `2018` versions, so that the packages are preserved.

@palmskog

**Comment by fpottier** [comment]
Le 24/01/2020 à 17:37, Guillaume Claret a écrit :
> It seems to us that the following version of |coq-menhirlib| are not 
> available anymore:

You are right, my bad! I just removed the old coq-menhirlib repository
but did not think that it was still serving archives for opam.

Unless Jacques-Henri has kept his local copy (which would allow us to
recreate the repository), I think it would be simplest to remove these
old versions from opam.

-- 
François Pottier
francois.pottier@inria.fr
http://gallium.inria.fr/~fpottier/

**Comment by fpottier** [comment]
PS. 20200121 can definitely be deleted,
as it corresponds to a version of Menhir
that did not make it to opam on the OCaml side.

-- 
François Pottier
francois.pottier@inria.fr
http://gallium.inria.fr/~fpottier/

**Comment by clarus** [comment]
OK thanks, done for removing version `20200121`.

**Comment by jhjourdan** [comment]
@clarus : does any package depends on these versions of MenhirLib?

If so, then we should keep these in one way or another. Otherwise, then let's remove these packages.

**Comment by clarus** [comment]
According to the command `opam search --depends-on=...` no public packages depend on these versions (this does not exclude local developments with a local `.opam` file).

**Comment by jhjourdan** [comment]
Ok. Then let's remove the package and see if someone complains.

If someone is affected then:
1- It should not be difficult to port to a slightly more version of Menhir
2- I have a copy of the git repo on my laptops.

**Comment by clarus** [comment]
OK thanks, I did all the removal, now closing the issue!
