### ISSUE TITLE
Intruders among the list of categories on the web page collecting packages

### ISSUE THREAD

**Issue by herbelin** [coq/opam-coq-archive#1209]
It seems that a keyword libValidSDP (resp ValidSDP) accidentally arrived in the category field of the description of package coq-libvalidsdp (resp coq-validsdp). This shows in the list of categories [here](https://coq.inria.fr/opam/www). If it is clear that this is accidental, I may open a PR to fix it if needed.

**Comment by erikmd** [comment]
Hi @herbelin, indeed given the structure of the other *categories* (which all contain a `/`), I guess this was not intended when @proux01  had submitted the coq-libvalidsdp/coq-validsdp packages in the first place, so if `libValidSDP`/`ValidSDP` are just *keywords* that'll be very fine.
Thanks for raising that issue and sorry for the inconvenience…

**Comment by silene** [comment]
Closing, since this has been fixed.
