### ISSUE TITLE
Some packages are missing a "synopsys" line on the opam website

### ISSUE THREAD

**Issue by herbelin** [coq/opam-coq-archive#1210]
Some packages are missing a one-line description (synopsis field) on coq.inria.fr/opam/www. This should not be a problem per se, but the rendering displays `""` which looks strange. This is the case for instance of all mathcomp packages. Strangely, the `opam` source files seem to have a synopsys field, so, the problem is maybe only in the rendering engine.

**Comment by palmskog** [comment]
I've reported this before in #691, perhaps we can continue the discussion there to avoid duplication? It appears to be a problem in the website generation scripts.

**Comment by herbelin** [comment]
OK, closing as duplicate. I don't know how to help more though.
