### ISSUE TITLE
Can't install coqide using opam due to problems with gnome-icon-theme

### ISSUE THREAD

**Issue by mvanier** [coq/opam-coq-archive#1459]
The issue and a workaround are described here: https://github.com/coq/coq/issues/13229.

**Comment by MSoegtropIMC** [comment]
This should be fixed by ocaml/opam-repository#17463.

Actually CoqIDE (as Coq) live in the main opam repo (which also confuses me every now and again), so this is actually the wrong github repo to report this.

**Comment by palmskog** [comment]
We still have development packages of CoqIDE here, so this is valuable information. I will do a PR to fix those development packages, which unfortunately will not help regular users.

**Comment by MSoegtropIMC** [comment]
This is fixed on all release packages for CoqIDE with PR (https://github.com/ocaml/opam-repository/pull/17463) which just has been merged.
