### ISSUE TITLE
Question about EXTRA_OPAM_OPTION / EXTRA_FLAGS 

### ISSUE THREAD

**Issue by erikmd** [coq/opam-coq-archive#1499]
Cc @palmskog @gares

By taking a look at #1498, I saw there's an `EXTRA_OPAM_OPTION` variable in `.gitlab-ci.yml`:
https://github.com/coq/opam-coq-archive/blob/b258b1194d5109d28f1b516020b777a18a8a32d0/.gitlab-ci.yml#L122
but I am puzzled to see that this variable does not seem to be used; there is only `EXTRA_FLAGS `:
https://github.com/coq/opam-coq-archive/blob/e1fb37fbf6ebaacbe1e446223d7b2f052b2cc222/scripts/opam-coq-init#L10
Should one of these variables be renamed to the other?

Sorry if I missed something and the code is OK actually.

**Comment by gares** [comment]
I don't know sorry

**Comment by palmskog** [comment]
No precise idea here either. It may be some remnant from the OPAM 1 days.

**Comment by clarus** [comment]
This option appears in https://github.com/coq/opam-coq-archive/blob/master/scripts/opam-coq-install-remove :
```sh
echo Check if $PKG_NAME_VERSION is installable
if opam install "$PKG_NAME_VERSION" -y --show-action $EXTRA_OPAM_OPTION; then
  set +e
  echo Installing $PKG_NAME_VERSION
  opam install "$PKG_NAME_VERSION" -y -v -v --with-test $EXTRA_OPAM_OPTION >> $LOG
```
I added that for the target `any` in order to test the install with whatever OCaml compiler fits. Does that answer your remark?

**Comment by erikmd** [comment]
Hi @clarus, yes, definitely! thanks for your feedback :)
