### ISSUE TITLE
upstream issue with Iris archives

### ISSUE THREAD

**Issue by gasche** [coq/opam-coq-archive#1724]
Several ICFP'21 artifact evaluators are encountering an error when trying to install Iris from the opam-coq-archive.

```
$ opam install coq-iris.3.3.0
The following actions will be performed:
  ∗ install coq-stdpp 1.4.0 [required by coq-iris]
  ∗ install coq-iris  3.3.0
===== ∗ 2 =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The sources of the following couldn't be obtained, aborting:
          - coq-iris.3.3.0: Bad checksum
          - coq-stdpp.1.4.0: Bad checksum
```

The [current iris .opam file](https://github.com/coq/opam-coq-archive/blob/d7697bc/released/packages/coq-iris/coq-iris.3.4.0/opam) gives an archive URL <https://gitlab.mpi-sws.org/iris/iris/repository/iris-3.4.0/archive.tar.gz>, but this URL is now invalid (it brings to a login page).

I encountered this issue with a different gitlab instance recently ( https://github.com/ocaml/opam-repository/pull/18529#issuecomment-842414679 ); the problem is that a gitlab update changed the URL download scheme.

Could the packages be fixed with a new, valid URL? (This is moderately urgent; artifact evaluation!)

cc @RalfJung

**Comment by Zimmi48** [comment]
FWIW, the correct URL should now be https://gitlab.mpi-sws.org/iris/iris/-/archive/iris-3.4.0/iris-iris-3.4.0.tar.gz.

The scheme we have been using in Coq's CI is https://gitlab.mpi-sws.org/iris/iris/-/archive/iris-3.4.0.tar.gz and it does still work.

**Comment by gasche** [comment]
When I complained to gitlab.inria.fr engineers about the URL change, they suggested using a direct "API" endpoint, that they suspect may be more stable over time:

https://gitlab.inria.fr/api/v4/projects/fpottier%2Fmenhir/repository/archive.tar.gz?sha=20210419

The same approach may work for other gitlab instances.

**Comment by RalfJung** [comment]
Argh, gitlab changing download links is quite annoying. :/

**Comment by RalfJung** [comment]
Should be fixed by https://github.com/coq/opam-coq-archive/pull/1725

**Comment by gasche** [comment]
Thanks @Zimmi48 and @RalfJung for the prompt fix!
