### ISSUE TITLE
Packages for 8.7.dev and 8.7 beta differ

### ISSUE THREAD

**Issue by gares** [coq/opam-coq-archive#182]
The diffed in the license for example.

**Comment by gares** [comment]
@Zimmi48

**Comment by Zimmi48** [comment]
You mean coq.dev, I suppose? This one looks like it needs fixing indeed.
Quick note: I made the 8.7 beta package as part of the release project, but I am not the well suited person to maintain any OPAM package given that I don't personally use OPAM.

**Comment by mattam82** [comment]
Hmm, I don't understand what's the issue here. I'll test and fix the 8.7.dev package

**Comment by mattam82** [comment]
Ok, there were minor differences between them. Fixed now, and the 8.7.dev package builds fine as well.

**Comment by Zimmi48** [comment]
coq.dev says the license is "LGPL 2" instead of "LGPL 2.1", the opam version is 1.1, the maintainer is clarus. I think that this was what @gares was referring too...
