### ISSUE TITLE
Since 8.7~ coq byte is no more built/installed

### ISSUE THREAD

**Issue by gares** [coq/opam-coq-archive#183]

**Comment by gares** [comment]
@Zimmi48

**Comment by Zimmi48** [comment]
Indeed, but should it? @letouzey

**Comment by ejgallego** [comment]
Certainly if people is expected to be able to build / develop plugins, etc... from the opam install, the byte targets should be installed by it.

**Comment by mattam82** [comment]
I tend to agree with @ejgallego that it's useful to have the bytecode version, so people can debug with coqtop.byte tracing, but is that the only reason to have it?

**Comment by ejgallego** [comment]
Yeah mainly for developers, for instance I think @gares build jsCoq [which requires the bytecode version] from OPAM .

**Comment by gares** [comment]
Exactly, I need the bytecode version to be installable by opam.
It is easy to fix by adding a `make byte` and `make install-byte` or something like that.
An alternative is to provide a `coq-byte` package, but I think the former option is much simpler.

**Comment by Zimmi48** [comment]
OK, can I let you fix this? It would take me longer than you to fix it because on this machine I haven't installed OPAM (so just fixing this and testing it would require compiling OCaml, etc.)

**Comment by gares** [comment]
ok, I'll do it

**Comment by gares** [comment]
Done.  I guess I should not be the one clicking the merge button.
I've tested it locally. Unfortunately I had no time to setup travis here ;-/

**Comment by Zimmi48** [comment]
OK I've added a few comments. In the end though, I don't personally enjoy merge privileges on this repo so someone else has to click the merge button.
