### ISSUE TITLE
coq 8.14.0 linking error in opam

### ISSUE THREAD

**Issue by lzheng5** [coq/opam-coq-archive#1888]
Hello,

So I got the following linking error. 

```
⬇ retrieved coq.8.14.0  (cached)
[ERROR] The compilation of coq.8.14.0 failed at "make COQ_USE_DUNE= -j3".

#=== ERROR while compiling coq.8.14.0 =========================================#
# context     2.1.0 | macos/x86_64 | ocaml.4.13.1 | https://opam.ocaml.org#78f7e61d
# path        ~/.opam/default/.opam-switch/build/coq.8.14.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make COQ_USE_DUNE= -j3
# exit-code   2
# env-file    ~/.opam/log/coq-32861-5655a1.env
# output-file ~/.opam/log/coq-32861-5655a1.out
### output ###
# Undefined symbols for architecture x86_64:
# [...]
#   "___gmpz_mfac_uiui", referenced from:
#       _ml_z_facM in libzarith.a(caml_z.o)
#   "___gmpz_primorial_ui", referenced from:
#       _ml_z_primorial in libzarith.a(caml_z.o)
# ld: symbol(s) not found for architecture x86_64
# clang: error: linker command failed with exit code 1 (use -v to see invocation)
# File "caml_startup", line 1:
# Error: Error during linking (exit code 1)
# make[1]: *** [_build/install/default/bin/coqc] Error 1
# make[1]: *** Waiting for unfinished jobs....
# make: *** [submake] Error 2
```

I am on macOs 10.15.4 and I have zarith.1.12 installed.

Any workaround?

**Comment by lzheng5** [comment]
I have installed exenum, parsley, bitvec, primes. 

But none of them showed any problems.

Not really sure what to do with the link error. Instead, I just downloaded the Coq.8.13.2 mac installer, which has already contained the package I wanted to use. 

I guess you may close this issue if you want.

**Comment by ejgallego** [comment]
In my experience these kind of issues are rarely one offs, so indeed maybe we can move this to coq repos given your input.

Thanks for the feedback!

**Comment by MSoegtropIMC** [comment]
> How did you install gmp? brew? macports?
> cc @MSoegtropIMC

sorry for the delay - was on vacation. I regularly try both in VMs. Locally I use MacPorts, Coq Platform CI uses Homebrew. So I would say both are well tested.

@lzheng5 : did you try the Coq Platform scripts? It is safe to try this since they create a new opam switch and won't touch anything you have. In case this does not work, please report a bug at Coq Platform. If Coq Platform works, I would consider using this unless you need a different OCaml version for some reason.
