### ISSUE TITLE
coqide vs coq:coqide

### ISSUE THREAD

**Issue by clarus** [coq/opam-coq-archive#19]
There are currently two packages for CoqIDE:
* [coqide](http://opam.ocaml.org/packages/coqide/coqide.8.4.6/) on the OCaml repository
* [coq:coqide](http://coq.io/opam/coq:coqide.8.5~beta3.html) on the Coq repository

Proposal:
* rename `coq:coqide` to `coqide`
* put the stable versions of CoqIDE on the OCaml repository, the non-stable ones on `extra-dev`

This does not completely follows our conventions for Coq packages (naming, ...), but is justified for historical compatibility.

**Comment by gares** [comment]
coq:coqide is not there anymore, closing the issue
