### ISSUE TITLE
CompCert 64-bit versions

### ISSUE THREAD

**Issue by mindbound** [coq/opam-coq-archive#196]
I've noticed that all CompCert versions in the repo have only ia-32 builds enabled. The [CompCert manual states](http://compcert.inria.fr/man/manual002.html#sec21) that one should be able to compile native 64-bit versions of the compiler, using `x86_64-<OS>` configure flags. Could this be added?

**Comment by ybertot** [comment]
It is sensible, but for now I have a question: how do we detect if the hosting machine is 32 or 64 bits? The os variable provided by opam does not seem to be that precise.

**Comment by silene** [comment]
> how do we detect if the hosting machine is 32 or 64 bits? The os variable provided by opam does not seem to be that precise.

That is because the information is stored in another variable:

    $ opam config list
    ...
    arch                 x86_64               # The current arch, as returned by "uname -m"
    ...

That said, I don't know what the policy with respect to CompCert should be. Is the opam package meant to compile only the native version? Should there be one opam package per processor / operating system (or at least a few common configurations)?

**Comment by mattam82** [comment]
That’s a question for @xavierleroy I think

**Comment by xavierleroy** [comment]
CompCert can easily be set up as a cross-compiler (producing code for a different platform than the host platform running CompCert) but additional libraries and tools will be needed for it to run.  For example, if the host platform is x86-64 Debian or Ubuntu,
* for x86-32 (ia32), the libc6-dev-i386 library package must be installed;
* for ARM, you need cross-assembler and cross-linker, e.g. the gcc-arm-linux-gnueabihf package, and qemu to run the test suite;
* for PowerPC, it's something like gcc-powerpc64-linux-gnu.

My advice is to not bother with cross-compilation and build only the version of CompCert that corresponds to the host platform.  At AbsInt and at Inria we have CI for CompCert that exercises all the supported target platforms.

**Comment by mattam82** [comment]
Ok. So we should just ensure that on 64 bits architecture compcert 3 builds the right version, of I understand correctly

**Comment by llelf** [comment]
How should this be done?  Should I open a pull request for the existing `…/coq-compcert.3.6/opam`?

**Comment by clarus** [comment]
@mindbound So now it seems that CompCert builds by default in 64 bits mode https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-compcert/coq-compcert.3.8/opam , plus there is a `coq-compcert-32` package for those who want the 32 bits version. Does that correspond to your needs?

**Comment by mindbound** [comment]
It does, thank you very much!
