### ISSUE TITLE
Indexes not correctly updatd

### ISSUE THREAD

**Issue by gares** [coq/opam-coq-archive#227]
Look here:
  https://coq.inria.fr/opam/core-dev/
the packages directory has a time stamp more recent than the index one, indeed the index contains an outdated version of the packages.

**Comment by gares** [comment]
I've no access to the web server running the scripts that generated the index, hence I'm assigning it to @maximedenes

**Comment by maximedenes** [comment]
I don't know where this script is running, I've asked many times before. @mattam82 @letouzey do you know?

**Comment by maximedenes** [comment]
In @mattam82 's crontab I see the following (commented) line:
```
#*/10 * * * * cd /nas/common1/pir2/coq.inria.fr/opam && sh update_opam_git.sh
```

**Comment by mattam82** [comment]
I’ve added the script to the repo last time you asked, do you need
privileged access to fix this? The cron job is run by root now, this was a
temporary measure.
Le lun. 20 nov. 2017 à 11:53, Maxime Dénès <notifications@github.com> a
écrit :

**Comment by gares** [comment]
Something goes wrong with the script, but the email with the error is sent to `root` and I've no clue who reads the emails.. We can easily change https://github.com/coq/opam-coq-archive/blob/6200ac26252e777ddded58c7c7268bf75ff8deaa/scripts/refresh-opam-indexes#L5 but it must point to a guy that has access to the machine, which I don't have.

**Comment by gares** [comment]
Oh, assuming `mail` works on that machine...

**Comment by letouzey** [comment]
See my [comment](https://github.com/coq/opam-coq-archive/issues/229#issuecomment-346575753) to #229 . Concerning the initial problem, our crontab file `/etc/cron.d/coq` isn't correctly installed when the webserver (re)boot. More precisely, the crontab daemon starts too early, when network disks and ldap users aren't available yet. That could be solved by a mere `sudo service crontab restart` manually later, but that's a pain nonetheless. I've notified the staff guys (SIC-PRO) of this issue, no answer yet.
