### ISSUE TITLE
no (working) smtp on the machine serving the opam archive

### ISSUE THREAD

**Issue by gares** [coq/opam-coq-archive#229]
Now the archive is updated again, but I did receive no notification that it stopped working.

The update script uses `mail` to send a mail to root (and myself), but is seems not to work since I received no email.

Again, I don't have access to that machine, so I cannot fix nor investigate the issue.

**Comment by mattam82** [comment]
Apparently root gets no mail either. I'm trying to see if there's something in the logs

**Comment by mattam82** [comment]
Nothing in the syslog either...

**Comment by mattam82** [comment]
Actually if I do ``./scripts/refresh-opam-indexes released`` in opam/ there's no error, so no report

**Comment by mattam82** [comment]
Shall I just make a false error report then, to test this?

**Comment by mattam82** [comment]
mail seems to work independently, but I'm a bit suspicious of the "notify()" definition:
``(echo "OPAM $1 on repo $2 failed:"; cat $LOG) | mail -s 'OPAM alert' $MAILTO
echo "OPAM $1 on repo $2 failed:"; cat $LOG``

Shouldn't there be a semicolon after MAILTO or something?

**Comment by gares** [comment]
there should be an end of line...

btw, I'm now receiving email by you with alerts about the command being called from a directory that does not contains any packages

**Comment by mattam82** [comment]
Yes, I launched the script in the wrong dir at first. So mail works :) You should get a success mail now

**Comment by mattam82** [comment]
Indeed there is a newline

**Comment by gares** [comment]
ok, thanks

**Comment by mattam82** [comment]
Wait a second, is it ok that core-dev is not updated?

**Comment by letouzey** [comment]
Sorry to come late in the discussion. To answer old questions, the script runs on our webserver `coq.paris.inria.fr`. Of course there is an smtp running there, simply none of us is root on this machine, that's the staff guys (SIC-PRO) who are, we are just sudoers, so we do not receive the mails to root. For all our scripts, I suggest sending errors or warning to `coq-www@inria.fr`, that's currently me, @mattam82, @maximedenes and @herbelin, and could be extended if needed.
