### ISSUE TITLE
Fix version constraints

### ISSUE THREAD

**Issue by Zimmi48** [coq/opam-coq-archive#233]
The large number of red boxes here https://coq-bench.github.io/clean/Linux-x86_64-4.05.0-1.2.2/released/ seems to indicate that a number of packages in released do not correctly state their Coq version constraints. This should be fix but I've no will to do it myself.

**Comment by herbelin** [comment]
On the first 5 five I looked at, there is no problem of Coq version constraints.
- color, corn, flocq, high-school-geometry: opam-version problem detected by lint (error on finding `1.0`, is the linter too strict or does the version really matter? But if so, does this mean that different opam files are needed for different opam version?)
- ergo: missing files in uninstall target
- ...

**Comment by Zimmi48** [comment]
Ah OK, then it's just that this bench is too strict. Sorry for the noise. Let's close this issue.

> But if so, does this mean that different opam files are needed for different opam version?)

Yes, there is a change of format between 1.2 and 2.0. The opam team has written a bot that automatically updates the [2.0.0 branch on the opam repo](https://github.com/ocaml/opam-repository/tree/2.0.0) following changes in the master branch.

**Comment by Zimmi48** [comment]
The files are not that different, see e.g. here https://github.com/ocaml/opam-repository/blob/2.0.0/packages/coq/coq.8.7.0/opam but include the url (that's one difference).

**Comment by herbelin** [comment]
Sorry, I did not get it. What should we do then? To have two opam files, one for opam 1, and one for opam 2? Two opam repositories?

**Comment by Zimmi48** [comment]
I don't really know how that will work but I wouldn't worry too much about this until opam 2.0 is actually released. Maybe setting the `opam-version` variable would be a good move though (I don't know).
