### ISSUE TITLE
rewrite archive2web using opam-file-format

### ISSUE THREAD

**Issue by gares** [coq/opam-coq-archive#235]
[archive2web](https://github.com/coq/opam-coq-archive/blob/master/scripts/archive2web) currently parses the opam file in a very fragile way.
[opam-file-format](https://github.com/ocaml/opam-file-format) should be used instead.

This will make it possible to output the version of Coq supported by the package as part of the package description.

**Comment by gares** [comment]
@maximedenes for reference

**Comment by gares** [comment]
FTR, such library was not there when archive2web was written :-/

**Comment by gares** [comment]
wip:  https://github.com/gares/opam-coq-archive/tree/rewrite/archive2web

**Comment by gares** [comment]
@maximedenes I worked a bit on the code during the WG.
There are two things left to do:
- test/fix the parsing of Coq versions. The AST is complex, not sure how to proceed when you read ">= 8.4  & < 8.8~" I gess you want to generate "8.4, 8.5, 8.6, 8.7" otherwise the search facility of the package index gets much harder to code.
- the output, html of json?  The code is today based on a template html file where `@@PACKAGES@@` gets assigned to the data in html format. We could write the data in json and have the page populate its own DOM tree running some js code (that would download the json file via http), but I'm not very fluent in js
- the js code uses the DOM tree to store the data, while an MVC approach would probably be better...

**Comment by gares** [comment]
CC: @vbgl

**Comment by gares** [comment]
see also the opam package `opam2web`. Last time I checked the output was ugly, but it may have improved

**Comment by Zimmi48** [comment]
It is what is used by https://opam.ocaml.org/packages/. I think this is more pretty / less ugly than the Coq package index.

**Comment by gares** [comment]
Last time I checked, it was not ;-) So maybe the package was just outdated.
I'm all for killing my first, an hopefully last, js code so feel free to replace the coq package index on the spot.
It may need a bit more filtering options, especially based on the version of Coq (we don't have it today, but the website at that link only has text search AFAICT)

**Comment by gares** [comment]
Also, the (very useful) popularity thing must need some external support (eg apache logs), since from the package metadata you simply can't infer that.

**Comment by maximedenes** [comment]
I'm looking at this again.

**Comment by maximedenes** [comment]
@gares Can this be closed? I implemented the JSON generation based on opam-file-format some time ago, and made the website use it. We still have to implement some new features (consolidation of supported Coq versions, popularity, etc), but these would be better addressed in specific issues, I think.

**Comment by maximedenes** [comment]
Maybe the only remaining question is whether the old `archive2web` is still used, or if it can be safely removed. What used to launch it?

**Comment by gares** [comment]
the makefile I guess. I think it is unused

**Comment by maximedenes** [comment]
I think this can be closed now.
