### ISSUE TITLE
coq.dev install is failing

### ISSUE THREAD

**Issue by Zimmi48** [coq/opam-coq-archive#244]
```
$ opam install coq.dev
The following actions will be performed:
  ∗  install coq dev

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[coq] https://github.com/coq/coq#master already up-to-date

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] Installation of coq.dev failed
Processing  1/1: [coq: rm]
#=== ERROR while installing coq.dev ===========================================#
Some files in ~/.opam/4.05.0/install/coq.install couldn't be installed:
  - /home/theo/.opam/4.05.0/build/coq.dev/bin/coqmktop to /home/theo/.opam/4.05.0/bin
```

This might be related to coq/coq#6475 (`coqmktop` cannot be installed because it was removed) cc @ejgallego.
The strange thing is that I didn't manage to reproduce outside of the OPAM package.

**Comment by ejgallego** [comment]
Oh indeed the OPAM package is out of sync with the recent changes. I wonder what would be the best way here, adding the opam file to Coq could work, but it is not optimal. More modern approaches generate it automatically from the `make` system, but that's a lot of work.

What it is true is that the current setup is hard to test and maintain.

**Comment by Zimmi48** [comment]
@RalfJung has opened a PR to backport his recent changes, see #242.

On the topic of this issue though, I'd still like to understand what broke and why I can't reproduce it locally...

**Comment by ejgallego** [comment]
`coq.install` is trying to install a file that doesn't exist anymore, that part is pretty clear.

**Comment by Zimmi48** [comment]
Yes, my understanding went this far already ;)

**Comment by RalfJung** [comment]
Note that adding an `opam` file to the Coq repository makes it easier to pin that repo, but does not help for the problem here -- this opam archive still needs to be updated. That shouldn't be surprising; whenever anything packaging-related changes, opam needs to be updated.

I can extend #242 to also handle this.

**Comment by RalfJung** [comment]
Btw, the reason we have that list of files is solely for uninstalling. We could uninstall with a `rm -f` instead, which would make this less sensitive to removing files -- but adding new files would lead to them silently not be removed, which is horrible.

Does opam not have a way to track what gets installed? Or maybe we can use the `make uninstall` target?

**Comment by Zimmi48** [comment]
Thanks @RalfJung, I hadn't noticed that the file was listed explicitly in the files to install by OPAM.
I don't want to involve myself too much in the OPAM management (not my business) but I am a bit puzzled to see that the OPAM package does not simply install Coq using the appropriate install target and uninstall using the appropriate uninstall target. It would probably avoid issues if it were using these, *provided that we test these targets in our CI and make sure that we are not breaking them*.

It would also probably be good if this repository's CI could be extended to run a cron job rebuilding every package (that might not be reasonable so at least the packages that depend on a moving target, such as `coq.dev`).

**Comment by RalfJung** [comment]
> It would probably avoid issues if it were using these, 

I agree. I don't know what opam usually does; my entire opam knowledge stems from copying Coq's and ssreflect's opam file. ;)

>  (that might not be reasonable so at least the packages that depend on a moving target, such as coq.dev).

Good idea. I opened #246 for this purpose.
