### ISSUE TITLE
mtac2 not supported by 8.7.1

### ISSUE THREAD

**Issue by cartazio** [coq/opam-coq-archive#250]
what fraction of opam-coq supports 8.7 generally? 
should i switch to a previous release of ocaml and use 8.6?

**Comment by mattam82** [comment]
It’s hard to say how much is covered, you can look at the package index on coq.inria.fr and filter what is 8.7 compatible. And redirect your question to the devs of mtac2, @ziliani and @yurug I think

**Comment by maximedenes** [comment]
> filter what is 8.7

Last time I checked, the packages did not indicate the supported Coq versions. I plan to implement it, but if it is already done, please let me know.

**Comment by mattam82** [comment]
I see what you mean, they don't, it's just that some packages have 8.7 in their own version numbers

**Comment by ejgallego** [comment]
Seems fixed.
