### ISSUE TITLE
opam 2.0 switch

### ISSUE THREAD

**Issue by mattam82** [coq/opam-coq-archive#257]
We should try opam 2.0 at some point, the release candidate is out:
https://opam.ocaml.org/blog/opam-2-0-0-rc/

**Comment by Zimmi48** [comment]
It seems that, on the contrary, the question is whether we should keep this repo in 1.2 syntax as long as possible and add the main Coq packages here as well, to continue providing support to OPAM 1.2 users (see the discussion on Coq-Club). Indeed, OPAM 2.0 supports 1.2 syntax but the converse is not true.

**Comment by mattam82** [comment]
Yes, we should transition slowly it seems.

**Comment by ejgallego** [comment]
Certainly something we should do for the 8.10 timeframe is to move the `dev` packages to the OPAM 2.0 repository. I think that the main OPAM files in the Coq repos should move to 2.0 as this is what we will have to submit to ocaml/opam-repository so I think it is reasonable to ask `.dev` users to move to 2.0.

**Comment by Zimmi48** [comment]
>I think that the main OPAM files in the Coq repos should move to 2.0 as this is what we will have to submit to ocaml/opam-repository so I think it is reasonable to ask .dev users to move to 2.0.

Yes, this seems reasonable (cc coq/coq#8657).
So while core-dev and extra-dev could be migrated to 2.0, released should stick to 1.2 format for longer, and include packages for Coq itself.

**Comment by ejgallego** [comment]
Sounds good to me. But we'd need to open a different git repository then?

**Comment by Zimmi48** [comment]
Would we? We already distribute these three folders as three different OPAM channels.

**Comment by mattam82** [comment]
AFAIU the three repos are indeed independent and we could move some to 2.0
and not others. Maybe @gares knows better

**Comment by gares** [comment]
I think opam2 comes with a tool to convert packages. It should be enough to convert only the ones in *-dev. I think opam2 also needs a manifest file at the root, dunno if we have it. I don't have time for this now, if you have, please go ahead, the plan seems ok to me.

**Comment by vbgl** [comment]
What’s the status of this?

Is it time to move all the repos to opam2?

In particular, I think it would be great if the migration is complete before we start playing with version 8.10.

**Comment by ejgallego** [comment]
I'd say let's give a 1 month warning in coq-club, then move all of them.

**Comment by mattam82** [comment]
Now opam 2 is only used for the released branch, right? I think Enrico said we can freeze the 1.2 released repo and move it to opam 2 in parallel.

**Comment by gares** [comment]
opam is able to honor `repo` files like this one:
```
opam-version: "2.0"
browse: "https://opam.ocaml.org/pkg/"
upstream: "https://github.com/ocaml/opam-repository/tree/master/"
redirect: [
  "https://opam.ocaml.org/1.1" {opam-version < "1.2"}
  "https://opam.ocaml.org/1.2.0" {opam-version < "1.2.2"}
  "https://opam.ocaml.org/1.2.2" {opam-version < "2.0~"}
]
archive-mirrors: "cache"
stamp: "e9b406c9"
```

What they did is to move the git repo to the new format and still ship an old copy of the repo at the URL above. The old repo is not versioned (as far as I know).

So, first of all, I need @vbgl to think how to deploy things.
I can open a branch/PR with the archive switched to the new format to see how it goes, but before merging a copy of the old "deployment" has to be made (and tested with a 1.2 client) and the URL has to be part of the repo file.

I'm fine with a 1 month heads up on coq-club, but I'd like to figure out the details of the migration first.

**Comment by gares** [comment]
@mattam82 opam2 is used for core-dev and extra-dev, the main repo (released) is still in 1.2 format.

**Comment by mattam82** [comment]
Right, my mistake, I meant opam 1.2 is only used for released

**Comment by ejgallego** [comment]
Oh that's cool @gares

**Comment by Zimmi48** [comment]
In the WG @gares had proposed that the switch of the released repo happen at the beginning of the 8.10 beta. By waiting until that date, we give more chances that Debian Buster will have been released by then (as it includes opam2).

**Comment by vbgl** [comment]
What I fear is that doing two independent changes at once brought more problems and a harder time figuring out which change a given problem is related to.

**Comment by gares** [comment]
Yep, this is why I asked ;-)
If you want the opam 2 switch to happen before, I'll try to make the PR asap (it will take some time to fix linting errors and purge broken pkgs as I did for extra dev.
