### ISSUE TITLE
`repo` file needs to be added to `index.tar.gz`

### ISSUE THREAD

**Issue by RalfJung** [coq/opam-coq-archive#263]
For better opam 2 compatibility, the repositories should have a `repo` file. With #261 all our repos have such a file, but it doesn't have the intended effect because it is not included in the <https://coq.inria.fr/opam/released/index.tar.gz>.

Seems like the website generation needs to be updated. Is it enough to change <https://github.com/coq/opam-coq-archive/blob/master/scripts/refresh-opam-indexes>?

**Comment by mattam82** [comment]
Should be enough indeed
