### ISSUE TITLE
Unsynchronized web repository

### ISSUE THREAD

**Issue by clarus** [coq/opam-coq-archive#38]
It feels to me that the `released` repository, as available with:

    opam repo add coq-released https://coq.inria.fr/opam/released

is not synchronized any more, since the new version `2.2.1` of `coq-interval` is not available.

**Comment by clarus** [comment]
If someone has access to the script generating the HTTP version of the repository, and could relaunch it, I would be really thankful.

**Comment by mattam82** [comment]
Isn't it up-to-date now ?
-- Matthieu

**Comment by clarus** [comment]
OK, that works, thanks a lot!

**Comment by mattam82** [comment]
There was some moving of directories on the website, resulting in opam
pointing out
to an old copy.
