### ISSUE TITLE
problem when installing coq.8.0.dev

### ISSUE THREAD

**Issue by ybertot** [coq/opam-coq-archive#49]
Hello,

On a machine running fedora 21, I get the following error message

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of coq failed at "make world".

#=== ERROR while installing coq.8.0.dev =======================================#
# opam-version 1.2.2
# os           linux
# command      make world
# path         /user/bertot/home/tmp/certicartes/infra/opam/4.02.3/build/coq.8.0.dev
# compiler     4.02.3
# exit-code    2
# env-file     /user/bertot/home/tmp/certicartes/infra/opam/4.02.3/build/coq.8.0.dev/coq-3147-05296d.env
# stdout-file  /user/bertot/home/tmp/certicartes/infra/opam/4.02.3/build/coq.8.0.dev/coq-3147-05296d.out
# stderr-file  /user/bertot/home/tmp/certicartes/infra/opam/4.02.3/build/coq.8.0.dev/coq-3147-05296d.err
### stdout ###
# [...]
# bin/coqtop.opt -boot   -translate -strict-implicit -compile contrib7/romega/ReflOmegaCore
# bin/coqtop.opt -boot   -translate -strict-implicit -compile contrib7/romega/ROmega
# bin/coqtop.opt -boot   -translate -strict-implicit -compile contrib7/ring/NArithRing
# bin/coqtop.opt -boot   -translate -strict-implicit -compile contrib7/ring/Setoid_ring_theory
# bin/coqtop.opt -boot   -translate -strict-implicit -compile contrib7/ring/Setoid_ring_normalize
# bin/coqtop.opt -boot   -translate -strict-implicit -compile contrib7/ring/Setoid_ring
# bin/coqtop.opt -boot   -translate -strict-implicit -compile contrib7/cc/CCSolve
# bin/coqtop.opt -boot   -compile ide/utf8
# OCAMLC    ide/utils/okey.mli
# Makefile:580: recipe for target 'ide/utils/okey.cmi' failed
### stderr ###
# [...]
# Warning: unable to ensure the correctness of the translation of an if-then-else
# Warning: unable to ensure the correctness of the translation of an if-then-else
# Warning: unable to ensure the correctness of the translation of an if-then-else
# Warning: pattern step is understood as a pattern variable
# Warning: pattern step is understood as a pattern variable
# Warning: pattern step is understood as a pattern variable
# Warning: pattern step is understood as a pattern variable
# File "ide/utils/okey.mli", line 33, characters 16-33:
# Error: Unbound module Gdk
# make: *** [ide/utils/okey.cmi] Error 2

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  \u2217  install coq 8.0.dev
No changes have been performed

===========================================
As extra information I can also give information about the current opam set up:
Here are a few results of commands:

opam --version
1.2.2
opam list --root $INFRA/opam
# Installed packages for 4.02.3:
base-bigarray      base  Bigarray library distributed with the OCaml compiler
base-ocamlbuild    base  OCamlbuild binary and libraries distributed with the OC
base-threads       base  Threads library distributed with the OCaml compiler
base-unix          base  Unix library distributed with the OCaml compiler
camlp4           4.02+6  Camlp4 is a system for writing extensible parsers for p
camlp5             6.14  Preprocessor-pretty-printer of OCaml
lablgtk          2.18.3  OCaml interface to GTK+
ocamlbuild            0  Build system distributed with the OCaml compiler since 
ocamlfind         1.5.6  A library manager for OCaml

opam repo --root $INFRA/opam
  10 [http]    core-dev     https://coq.inria.fr/opam/core-dev
   0 [http]     default     https://opam.ocaml.org

**Comment by clarus** [comment]
The bench machine for OPAM cannot compile Coq `8.0.dev` either. This is a Ubuntu Linux version `15.10` (on this machine, the versions `8.1.dev`, `8.2.dev` and `8.3.dev` work well). I do not know how to solve this problem.

**Comment by herbelin** [comment]
I just tried on MacOS X with gtk installed with brew, and lablgtk 2.18.3 installed with opam. I got two problems: "sed" needs to be called with (typically) LC_ALL=C, and /usr/local/lib was not added properly to ld. Otherwise, it compiled fine.

Guillaume, what is the problem you observed?

Yves, can you check that the file ~/.opam/system/lib/lablgtk2/gtk.cmi is there. If not, it is maybe that gtk is not properly installed on your machine and opam could not fully installed lablgtk.

**Comment by ybertot** [comment]
J'ai refait l'expérience à partir d'une installation opam vide, et j'ai fixé le compilateur ocaml utilisé
```
cd /tmp
mkdir tryopamcoq8.0
INFRA=/tmp/tryopamcoq8.0/
opam init --root $INFRA/opam
opam switch 4.02.3 --root $INFRA/opam
opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev --root $INFRA/opam
opam install coq.8.0.dev --keep-build-dir --root=$INFRA/opam
```
La compilation échoue, et le fichier $INFRA/lib/lablgtk2/gtk.cmi est bien présent (et aussi un fichier gdk.cmi).

**Comment by herbelin** [comment]
Hi, I fixed a problem with the path to lablgtk. In particular, it now compiles fine on MacOS X. Would you mind trying again, and if it does not work, to send the coq-*-*.err file produced by opam (as mentioned in the error report).

**Comment by ybertot** [comment]
I just tried again, using the same command as in my previous comment.  It still fails, with the same error.  

The file given in attachment was found in 

/tmp/tryopamcoq8.0/opam/4.02.3/build/coq.8.0.dev/coq-2471-e0259d.err.  It has been zipped to make it acceptable for github.

[coq-2471-e0259d.err.zip](https://github.com/coq/opam-coq-archive/files/158400/coq-2471-e0259d.err.zip)

**Comment by herbelin** [comment]
What is the value of Coq_config.lablgtklib in directory config (i.e. in directory /tmp/tryopamcoq8.0/opam/4.02.3/build/coq.8.0.dev/config)? It should be $INFRA/opam/4.02.3/lib/lablgtk2, with the $INFRA being expanded, so that gtk.cmi can be found in this directory.

**Comment by clarus** [comment]
I also get the same error as @ybertot on my Ubuntu 14.04 machine, from a fresh `opam switch 4.02.3`:

```
File "ide/utils/okey.mli", line 33, characters 16-33:
Error: Unbound module Gdk
make: *** [ide/utils/okey.cmi] Erreur 2
```
Here is the content of my `coq_config.ml` file:

```
(* DO NOT EDIT THIS FILE: automatically generated by ../configure *)

let local = false
let bindir = "/home/guillaume/tmp/opam.8.0.dev/4.02.3/bin" 
let coqlib = "/home/guillaume/tmp/opam.8.0.dev/4.02.3/lib/coq"
let coqtop = "/home/guillaume/tmp/opam.8.0.dev/4.02.3/build/coq.8.0.dev"
let camllib = "/home/guillaume/tmp/opam.8.0.dev/4.02.3/lib/ocaml"
let camlp4 = "camlp5"
let camlp4lib = "/home/guillaume/tmp/opam.8.0.dev/4.02.3/lib/camlp5"
let lablgtklib = "/home/guillaume/tmp/opam.8.0.dev/4.02.3/lib/lablgtk2"
let best = "opt"
let arch = "x86_64"
let osdeplibs = "-cclib -lunix"
let version = "8.0pl3"
let caml_version = "4.02.3"
let versionsi = ""
let date = "Jan 2006"
let compile_date = "mars 06 2016 13:22:05"
let exec_extension = ""

let theories_dirs = [
"Arith";
"Bool";
"Init";
"IntMap";
"Lists";
"Logic";
"NArith";
"Num";
"Num/Leibniz";
"Num/Nat";
"Reals";
"Relations";
"Setoids";
"Sets";
"Sorting";
"Wellfounded";
"ZArith";
]
let contrib_dirs = [
"cc";
"extraction";
"field";
"first-order";
"fourier";
"funind";
"interface";
"jprover";
"omega";
"ring";
"romega";
"xml";
]
```

My `/home/guillaume/tmp/opam.8.0.dev/4.02.3/lib/lablgtk2` directory contains `gdk.cmi`, `gdk.cmx`, `gdk.ml` and `gdk.mli`.

**Comment by clarus** [comment]
A `Dockerfile` to reproduce the issue:

```
FROM ubuntu:15.10
MAINTAINER Guillaume Claret

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y apt-utils
RUN apt-get install -y gcc make git
RUN apt-get install -y curl m4
RUN apt-get install -y aspcud unzip
RUN apt-get install -y liblablgtk-extras-ocaml-dev

# User
RUN useradd --create-home user
USER user
ENV HOME /home/user

# Install OPAM
WORKDIR /home/user
RUN curl -L https://github.com/ocaml/opam/archive/1.2.2.tar.gz |tar -xz
WORKDIR opam-1.2.2
RUN ./configure && make lib-ext && make
USER root
RUN make install
USER user

# Configure OPAM
WORKDIR /home/user
RUN opam init
RUN opam switch 4.02.3
RUN opam repo add coq-released https://coq.inria.fr/opam/released
RUN opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
RUN opam install coq.8.0.dev -y --deps-only
```

Run with:

```
docker build --tag=coq.8.0.dev .
docker run -ti coq.8.0.dev /bin/bash
```

then:

```
opam install coq.8.0.dev
```

**Comment by herbelin** [comment]
Thanks. I pushed a new version which should solve the problem you encountered.

**Comment by clarus** [comment]
Thanks, this works for me!

**Comment by ybertot** [comment]
Works for me too, the compilation goes to the end. I still have a problem when running coqide, but it does start.

**Comment by herbelin** [comment]
With Coqide, I have a problem with some keys being interpreted as if with a modifier (e.g. d is inserting the Definition template). I could apply the patch which Jean-Marc Notin made for 8.1, which is to change Mod4 in the template menu to control-shift (as well as some other changes). Is that the same problem you have?

**Comment by herbelin** [comment]
I pushed the modifier change that Jean-Marc Notin's made for CoqIDE 8.1. Tested on MacOS X where CoqIDE is now apparently normally usable.

**Comment by ybertot** [comment]
The problem I have is exactly the one you describe, but I just recompiled an opam installation and the problem is still present.  Maybe you did not update the archive used by opam.  I am still using the script given on Feb. 29.

**Comment by herbelin** [comment]
Unfortunately, the ~/.coqiderc and ~/.coqide.keys files have to be regenerated so that the new bindings are taken into account. Otherwise, it takes the not-working bindings from the previous run of coqide. I don't know how to improve on this unless to add a check on a bad .coqiderc in the code of coqide itself, which somehow looks a bit excessive.

**Comment by ybertot** [comment]
Yes, after removing these files, it works.
