### ISSUE TITLE
Coq 8.8.2 package is broken

### ISSUE THREAD

**Issue by RalfJung** [coq/opam-coq-archive#502]
When I install Coq 8.8.2 (with Opam 2.0.1), I get
```
#=== ERROR while installing coq.8.8.2 =========================================#
Some files in /home/r/.opam/coq-test/.opam-switch/install/coq.install couldn't be installed:
  - /home/r/.opam/coq-test/.opam-switch/build/coq.8.8.2/bin/gallina to /home/r/.opam/coq-test/bin



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ ∗ install coq 8.8.2
└─ 
```
`opam show coq.8.8.2` points at this repository for the source of the package.

Cc @chdoc

**Comment by RalfJung** [comment]
The odd thing is that in another switch I have installed Coq 8.8.2 successfully...

**Comment by RalfJung** [comment]
An I cannot install the version from the "main" opam repositories either.

**Comment by RalfJung** [comment]
The gallina tool was removed on the 8.9 branch. So maybe it is using the wrong sources or so?

**Comment by RalfJung** [comment]
Turns out this is an old opam bug that got fixed a year ago but came back: https://github.com/ocaml/opam/issues/3651. Insert some lesson about test suites here, because opam clearly doesn't have one...

**Comment by Zimmi48** [comment]
Someone on gitter complained about a bug similar to this one where they thought they had installed Coq 8.8.2 but it turned out to be Coq 8.8.1 instead.
