### ISSUE TITLE
Package list is cut off due to improper escaping of coq-elpi description

### ISSUE THREAD

**Issue by tchajed** [coq/opam-coq-archive#508]
The package index at https://coq.inria.fr/opam/www/ cuts off in the middle of the coq-elpi package description because a backquote in the description isn't being properly escaped.

The immediate consequence is that filtering doesn't work, since its javascript file is included at the end.

**Comment by mattam82** [comment]
The problem is not the backquote but the following {{ in the description: 
yamlpp has a rule:
``| "{{" 
      { if !lang <> "en" then skip_until "en" 0 lexbuf; process lexbuf }
``
So it skips everything.

**Comment by mattam82** [comment]
I fixed it by passing the "-l en" flag to yamlpp, avoiding problems with this rule. The package index is functional again.
