### ISSUE TITLE
ci is not running

### ISSUE THREAD

**Issue by gares** [coq/opam-coq-archive#535]
@Zimmi48 is seems co is not running anymore on recent PRs.

**Comment by Zimmi48** [comment]
Sorry @gares, it seems that CI has been running (https://gitlab.com/coq/opam-coq-archive/pipelines) but has not been correctly reported as status check since fixing coq/bot#25. I'll fix this ASAP.

**Comment by Zimmi48** [comment]
Yep, that's pretty stupid in fact: the code of the bot had been made generic for the pushing to GitLab part but not for the status reporting part, so the CI status were reported to the Coq repository instead. I've reactivated GitLab's own GitHub integration for status reporting as a workaround until I get to make this part of the code of @coqbot more generic as well.

**Comment by Zimmi48** [comment]
Alright, this is now fix so I've disabled GitLab's GitHub integration for status check again. @coqbot should take care of this from now on.
