### ISSUE TITLE
coq-unicoq tarball contains a 1.3G .tex file

### ISSUE THREAD

**Issue by gares** [coq/opam-coq-archive#544]
It is called mathcomp.tex and contains a lot of unification problems... @beta-ziliani

**Comment by beta-ziliani** [comment]
it is not inside a compressed file? it should...

**Comment by gares** [comment]
sure, the tarball is 41M. That is fine, I was just wondering if i was done on purpose or not.

**Comment by beta-ziliani** [comment]
the file is meant to be preserved (in github): it's a very expensive run of the entire compilation of matchcomp with all its non-trivial unification problems, which could be interesting to analyze the common patterns and such. but if it should be in the tar file, probably not.
