### ISSUE TITLE
coq-paco versioning

### ISSUE THREAD

**Issue by vzaliva** [coq/opam-coq-archive#546]
- coq-paco-1.2.9 is compatible with coq-8.8.2
- coq-paco-8.7.0 is only compatible with coq-8.7

Since version '8.7.0' is considered newer than '1.2.9' opam complains that this package could not be upgraded without degrading coq and other packages. It is just a warning, but shows up on each `opam upgrade`.

As I recall coq-paco used to be in coq contribs archive and that's why it was using coq's version numbering. Then it was moved to separate project and used author's numbering. If it is not in contribs anymore I suggest following author numbering scheme.

P.S. To make things even more confusing, project web page states _"The current version is v1.2.8, and it's compatible with Coq 8.6.1, 8.7.2, and 8.8.1."_

**Comment by gares** [comment]
Could you please mention the maintainer of the package explicitly so that github notifies him?

**Comment by Zimmi48** [comment]
Yes, unfortunately the numbering scheme of coq-contribs does not play very nicely with the capacity of going back to a "normal" numbering scheme. In principle, already published packages should not be removed, but this is a case where I would consider this option (to leave only the official package and the official numbering scheme).

**Comment by vzaliva** [comment]
> Could you please mention the maintainer of the package explicitly so that github notifies him?

Not sure who maintainer is. It is "paco@sf.snu.ac.kr" in OPAM file.

**Comment by vzaliva** [comment]
@herbelin was who last touched the OPAM package in this repo

**Comment by gares** [comment]
IIRC opam versions do have the epoc feature exactly for that. I don't recall the syntax, but in Debian 1:1 is greater than 3, since there is an implicit 0: in front.

**Comment by Zimmi48** [comment]
Does not seem like it: https://github.com/ocaml/opam/issues/3537

**Comment by Zimmi48** [comment]
FTR @gilhur and @jeehoonkang seem to be the current maintainers according to the commit history.

**Comment by herbelin** [comment]
> coq-paco-8.7.0 is only compatible with coq-8.7

It is a mistake. I had locally removed coq-paco from #500 (since paco is managed outside coq-contribs), but I forgot to push the commit. I fix this in #547.

**Comment by vzaliva** [comment]
Fixed by https://github.com/coq/opam-coq-archive/pull/547
