### ISSUE TITLE
Missing dependencies on g++

### ISSUE THREAD

**Issue by sacerdot** [coq/opam-coq-archive#593]
* coq-hammer
  missing dependency on g++ (during make)
* coq-coquelicot, coq-flocq
  missing dependency on C++ compiler (during configure)

**Comment by silene** [comment]
That is right. Note, however, that the `conf-g++` opam package does not exist in the upstream 1.2 opam repository, so it might be worth waiting for the 2.0 switch before adding this dependency.

**Comment by clarus** [comment]
Thanks for the report! Should be fixed for `coq-hammer`.

**Comment by silene** [comment]
Closing, since it was also fixed for `coq-coquelicot` and `coq-flocq` (and other similar packages).
