### ISSUE TITLE
Complete list of broken 8.9.0 packages

### ISSUE THREAD

**Issue by sacerdot** [coq/opam-coq-archive#594]
Hello,
this is the complete list of root packages that are computed to be co-installable with coq 8.9.0 but that are broken:

coq-list-string
coq-quickchick
coq-unimath-foundations
coq-io-system-ocaml
coq-concurrency-proxy
coq-mathcomp-sum-of-two-square
coq-qcert

Cheers,
C.S.C.

**Comment by clarus** [comment]
Hi,

Do you confirm these packages are still broken? I think we fixed all of them.

**Comment by jeromesimeon** [comment]
PR #924 includes proposed fixes to the opam packages for earlier versions of `coq-qcert`.

**Comment by jeromesimeon** [comment]
> PR #924 includes proposed fixes to the opam packages for earlier versions of `coq-qcert`.

I take it back... Those multiple builds take too long. I will make separate PRs for earlier versions later.

**Comment by clarus** [comment]
@sacerdot 🐆 Thanks for the report, I am closing as I believe that all the packages are now fixed.
