### ISSUE TITLE
coq-stdpp not available for Coq 8.9

### ISSUE THREAD

**Issue by spitters** [coq/opam-coq-archive#625]
Why is stdpp stuck at <8.9 ?
@robbertkrebbers @RalfJung ?

**Comment by RalfJung** [comment]
std++ master works with Coq 8.9 (and Coq master). We are working on getting a new release out.

**Comment by spitters** [comment]
But then it's just a matter of updating this file isn't it?
<=8.9.0
https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-stdpp/coq-stdpp.1.1.0/opam

**Comment by RalfJung** [comment]
No, version 1.1.0 really does fail with Coq 8.9.

**Comment by spitters** [comment]
Thanks. Maybe it is possible to get stdpp in Coq CI? Then the coq-devs know when they break something.

**Comment by RalfJung** [comment]
stdpp is in Coq CI. We always make sure std++ master works with Coq master (as well as any supported stable version of Coq).

But that just means std++ gets adapted to work with new Coq versions. It doesn't mean releases happen automatically.

**Comment by RalfJung** [comment]
std++ 1.2.0 just got released, it will be added to this repo by https://github.com/coq/opam-coq-archive/pull/634.

**Comment by spitters** [comment]
Great. Thanks.

from my phone
