### ISSUE TITLE
The repository is huge

### ISSUE THREAD

**Issue by RalfJung** [coq/opam-coq-archive#626]
When I just pulled this repository, git downloaded about 500 MiB of stuff. Something seems wrong there.

Looking at the biggest git objects, it seems the the [gh-pages branch](https://github.com/coq/opam-coq-archive/tree/gh-pages) is mostly responsible for this. In particular, while usually this repository references external tarballs, that branch contains a copy of all of them:
```
$ du -csh released-opam1.2/archives/
503M	released-opam1.2/archives/
```
That seems quite excessive -- and, in particular, having to clone all of that when cloning this repo seems excessive.

Cc @vbgl

**Comment by vbgl** [comment]
That branch corresponds to that website: http://coq.github.io/opam-coq-archive/released-opam1.2/ It should be stored in a different repository, dedicated to this task.

Ping @gares

**Comment by gares** [comment]
We should also consider to drop, at some point, the frozen repo in 1.2 format. After all it was there just to be nice to users during the migration phase, but I guess nobody will use it for long. Then dropping the branch is going to suffice to shrink again the size of the repo. I'm not sure it is worth it to crate another repo. We should definitely set a deadline for removing the legacy repo, knowing that the switch happened 22 days ago, I believe it is reasonable to drop it in May. What do you think?

**Comment by RalfJung** [comment]
Why does the frozen repo have to *contain* the tarballs instead of referencing like it used to in the times of opam 1.2?

**Comment by vbgl** [comment]
It is not a frozen repo. It’s the frozen state of the website that is used by opam.

Rather than the source, it is the object.

**Comment by RalfJung** [comment]
Wait, https://coq.inria.fr/opam/www/ *mirrors* these tarballs?

**Comment by gares** [comment]
The 1.2 version was mirroring, or better `opam admin` was. I don't think opam 2 does it (btw).

**Comment by RalfJung** [comment]
Well there's still copies at https://coq.inria.fr/opam/released/archives/ -- but e.g. https://coq.inria.fr/opam/released/packages/coq-stdpp/coq-stdpp.1.0.0/opam does not reference them.

**Comment by RalfJung** [comment]
In fact, https://coq.github.io/opam-coq-archive/released-opam1.2/packages/coq-stdpp/coq-stdpp.1.0.0/url also refers to the original source, not the copy in `archives`...

**Comment by gares** [comment]
Mirroring may not be a bad idea: if the original tarball disappears, then the archive is still functional (Debian mirrors orig tarballs to). Here 99% of the tarballs are on github, so I'm not very worried about "random website being down", so I did not investigate why opam2 does not do it.

**Comment by gares** [comment]
(I'm not so sure it patched the url, you should look at the index at the root of the repo)

**Comment by RalfJung** [comment]
So opam somehow magically knows to fall back to `archives`? Interesting.

**Comment by gares** [comment]
No, see the end of http://coq.github.io/opam-coq-archive/released-opam1.2/urls.txt

**Comment by RalfJung** [comment]
Well that still doesn't explain how the URLs there are related to opam package names+versions.

**Comment by gares** [comment]
The file urls.txt has a list of files (local to the server) and their hash.
Similarly a package has a url and the hash of the file at that url.
I guess that is the hash also happen to be present locally, opam picks the local one (or falls back to it).
I think opam also a cache local to your opam root. I imagine the mechanism is the same.

Anyway, I hope it is clear why the repo is big. I've a plan to make is small again. The only question mark is when...

**Comment by mattam82** [comment]
I would say early june is fine. While I'm sure many are still on the 1.2 repo, it's better to "entice" them to move to opam 2 sooner than later.

**Comment by Alizter** [comment]
Any progress with this? Seems to still be an issue.

**Comment by Alizter** [comment]
@gares Can we drop that branch now?

**Comment by gares** [comment]
I guess so
