### ISSUE TITLE
index.tar.gz for deployed archives is not getting regenerated

### ISSUE THREAD

**Issue by palmskog** [coq/opam-coq-archive#730]
As per #728, although merged new and modified `extra-dev` packages end up in https://coq.inria.fr/opam/extra-dev/packages/ properly, the repository's `index.tar.gz` file in https://coq.inria.fr/opam/extra-dev/ is not getting properly regenerated on deployment. This means that clients don't see the updated and new packages.

**Comment by palmskog** [comment]
This problem appears to be solved now, I can see the latest packages in `index.tar.gz`. I will reopen this issue if the problem reappears. cc: @erikmd

**Comment by erikmd** [comment]
@palmskog thanks! I restarted the build, so `coqorg/coq:8.10 = coqorg/coq:8.10-beta1` should be available in 90' or so.

**Comment by palmskog** [comment]
@mattam82 @gares @silene right now we are not getting proper regeneration of `index.tar.gz` for either `extra-dev` or `released`. For example, MathComp 1.9.0 packages are not present in https://coq.inria.fr/opam/released/index.tar.gz despite them getting merged before the timestamp of that file. Something strange is likely going on with the web server machine. Coq-club also has a [user report](https://sympa.inria.fr/sympa/arc/coq-club/2019-05/msg00077.html) about this. 

For `extra-dev`, my somewhat recent [merge](https://github.com/coq/opam-coq-archive/commit/fbe97ae21ee8f30825e818db1a6ed5187d5152d6) of `coq-fcsl-pcm` is still not reflected in `index.tar.gz`, although the `packages` directory has the update (cc: @anton-trunov).

**Comment by mattam82** [comment]
As said in the other issue, there’s an issue with NFS locks and opam preventing the index from being generated correctly. I made an issue on the opam github but didn’t hear back yet. I’ll try and contact the admins of coq.inria.fr to see if I can change the lock configuration, maybe that will solve it. In the meantime we could try to do the opam admin stuff in another directory and copy back the results.

**Comment by palmskog** [comment]
Right, the [discussion](https://github.com/coq/opam-coq-archive/pull/728#issuecomment-496251664) in that issue seemed to indicate it was due to some interaction between NFS and `opam admin`, specifically that the latter uses the `lockf` Unix system call. I looked a bit at the OPAM source and it doesn't seem like one can disable the use of `lockf` easily (which at least according to [this source](https://gavv.github.io/articles/file-locks/) works fine on NFS mounts). 

According to [this discussion](https://serverfault.com/questions/61594/what-does-no-locks-available-mean) there are a couple of possible causes that should likely be checked by administrators of the NFS server:

- the lock daemon (`lockd`) may not be running on the NFS server
- the NFS volume is full (unlikely since packages can get added)

**Comment by mattam82** [comment]
Ah, thanks for the help, I’ll check if lockd is running indeed !

**Comment by mattam82** [comment]
Otherwise it seems the mount option saying local_lock=none can’t be good.

**Comment by palmskog** [comment]
Another recommendation made in the thread (and which I have used to solve NFS problems before) is to unmount and remount the NFS volume on the client. This could rule out a problem with a stale mount.

Note that `local_lock=none` [means](https://linux.die.net/man/5/nfs) that lock requests are getting sent to the NFS server for sure, so it doesn't rule out a dead/failing `lockd` as explanation.

**Comment by palmskog** [comment]
If indeed `lockd` is running, I would try remounting with `local_lock=all` or `local_lock=posix`, which would mean all `lockf` calls by `opam admin` are never sent to the server.

**Comment by mattam82** [comment]
I tried a bit unmounting before but the device was always busy even when `lsof` didn’t list anything open there and no processes had their working dir in there. Do you have a tip for that too? :)

**Comment by palmskog** [comment]
`mount -o remount /mountpoint` might work to do a plain remount, but as far as I understand one can't change any options for an NFS mount in that way.

To do a proper unmount is tricky, some open things may not show up without special `lsof` options. I can't do more than link to [this discussion](https://unix.stackexchange.com/questions/15024/umount-device-is-busy-why) which lists a number of things to try.

**Comment by mattam82** [comment]
No need! I managed to remount with the nolock option and rebuild indexes:
```
sozeau@coq:~/coq.inria.fr/opam/released$ tar ztf index.tar.gz |grep mathcomp-ssreflect.1.9.0
packages/coq-mathcomp-ssreflect/coq-mathcomp-ssreflect.1.9.0/
packages/coq-mathcomp-ssreflect/coq-mathcomp-ssreflect.1.9.0/opam
```
If it works for you, please confirm on coq-club so that everyone is aware it's fine now :)

**Comment by palmskog** [comment]
@mattam82 my test commit in #738 regrettably indicates that `index.tar.gz` is still not getting generated properly. Maybe you can check if the error is still the same and that the mounting option has been honored?

**Comment by mattam82** [comment]
The system has been remounted without the option, let me see why.

**Comment by mattam82** [comment]
There's an automounter on this machine which doesn't let me persistently set the lock option. I tried putting a screen session attached to the volume (and rebuilt released/index.tar.gz), not sure this will prevent remounts with the wrong option. I asked the sysadmin about how to fix that permanently.

**Comment by mattam82** [comment]
Well I just checked and it seems if I leave my screen session open no remounts happen, so that's a temporary solution.

**Comment by maximedenes** [comment]
I'm moving the website and the Coq Package Index page to a VPS that we can administrate. It should resolve this issue.

**Comment by mattam82** [comment]
I’m not a believer, but thank god!

**Comment by CohenCyril** [comment]
@maximedenes The coq website and the opam index seem not be available at the moment for ssl certificates reasons (everything looked fine 20 minutes ago I believe)
```
wget https://coq.inria.fr                           
--2019-06-14 10:28:02--  https://coq.inria.fr/
Résolution de coq.inria.fr (coq.inria.fr)… 51.91.56.51
Connexion à coq.inria.fr (coq.inria.fr)|51.91.56.51|:443… connecté.
OpenSSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
Incapable d’établir une connexion SSL.
```

**Comment by maximedenes** [comment]
Yes, the migration is in progress as I announced on coqdev.

**Comment by CohenCyril** [comment]
> Yes, the migration is in progress as I announced on coqdev.

oh ok, my mistake! Would you have estimates on the time remaining before migration completion?

**Comment by maximedenes** [comment]
> oh ok, my mistake! Would you have estimates on the time remaining before migration completion?

I'd say a few hours if everything goes fine (includes DNS propagation time).

**Comment by maximedenes** [comment]
@CohenCyril does it work for you, now?

**Comment by CohenCyril** [comment]
> @CohenCyril does it work for you, now?

It does, thanks!

**Comment by CohenCyril** [comment]
@maximedenes however, I just released finmap.1.3.1 but it does not show even after an update
```
<><> coq-mathcomp-finmap: information on all versions <><><><><><><><><><><><><>
name         coq-mathcomp-finmap
all-versions 1.0.0  1.1.0  1.2.0  1.2.1
```
... has the package index been regenerated?

**Comment by maximedenes** [comment]
I'm putting back the auto regeneration.

**Comment by maximedenes** [comment]
Should be fixed now, feel free to reopen if the problem show up again.

**Comment by CohenCyril** [comment]
> Should be fixed now, feel free to reopen if the problem shows up again.

Works for me, thanks!
