### ISSUE TITLE
Invalid contrib homepages

### ISSUE THREAD

**Issue by clarus** [coq/opam-coq-archive#78]
Hi,

The following packages do not seem to have a valid homepage, and may be referring to the wrong sources:
* `projective-geometry.8.5.0`: https://github.com/coq-contrib/projective-geometry
* `regexp.8.5.0`: https://github.com/coq-contrib/regexp
* `tait.8.5.0`: https://github.com/coq-contrib/tait
* `tortoise-hare-algorithm.8.5.0`: https://github.com/coq-contrib/tortoise-hare-algorithm

**Comment by matej-kosik** [comment]
You are right.
The commit https://github.com/coq/opam-coq-archive/commit/fe76e3df4011a1fa519efc5b1aa5fc5dba0cedc0 fixes the wrong homepage links.

I am looking now at the download links.

**Comment by clarus** [comment]
Thanks!

**Comment by clarus** [comment]
Actually I just realized that most of the contribs had a missing `s` to their homepage links, so I added this pull-request to fix that: https://github.com/coq/opam-coq-archive/pull/79

**Comment by matej-kosik** [comment]
That was my fault. Thanks for spotting the typos and the pull-request. I've merged it.
