### ISSUE TITLE
coq-mathcomp-odd-order.1.6.1 mixing build and install

### ISSUE THREAD

**Issue by clarus** [coq/opam-coq-archive#802]
For the package `coq-mathcomp-odd-order.1.6.1` the build phase is as follows:
```
build: [ 
     [make "-C" "mathcomp/field" "-j" "%{jobs}%"]
     [make "-C" "mathcomp/field" "install"]
     [make "-C" "mathcomp/odd_order" "-j" "%{jobs}%"]
]
```
We could be tempted to move the `make ... install` out of the build phase, but it is required for the next line. However, installing files in the build phase is forbidden by Bubblewrap and opam so this package is currently broken.

Is there a solution? If not, should we remove this package?

**Comment by palmskog** [comment]
This is an old release that not many people are likely to install, so I don't think it's a big deal that it's broken right now. One possibility may be to create a separate package based on the same tarball (`coq-mathcomp-field-extra`?) with the additions from the `field` directory, and make this package depend on that package.

**Comment by clarus** [comment]
Good idea, I will make it, thanks.
