### ISSUE TITLE
Lots of spurious CI failures

### ISSUE THREAD

**Issue by palmskog** [coq/opam-coq-archive#818]
For nearly every pull request, I'm seeing spuriously failed jobs that get stuck on something trivial like compiling the OCaml compiler:
```bash
[ERROR] The compilation of ocaml-base-compiler failed at "/builds/coq/opam-coq-archive/opam-root-4.05.0/opam-init/hooks/sandbox.sh build ./configure -prefix /builds/coq/opam-coq-archive/opam-root-4.05.0/4.05.0 -with-debug-runtime".
```
See an example [here](https://gitlab.com/coq/opam-coq-archive/-/jobs/245151960).

After I restart them 1-2 times, they usually pass. @maximedenes could this be related to recent CI configuration changes for JSON generation?

**Comment by silene** [comment]
Maybe it is a coincidence, but it seems that all the jobs that failed were run on `pyrolyse`.

**Comment by gares** [comment]
```
### output ###
# Creating new namespace failed: Operation not permitted
```
IIRC there is an issue on pyrolise with --sandbox (does not work there). It was recently enabled.

**Comment by Zimmi48** [comment]
FTR I have root access to pyrolyse, so if someone tells me exactly how to install the missing package, I might be able to do it...
