### ISSUE TITLE
Failing coq.dev build in CI for 4.05.0

### ISSUE THREAD

**Issue by palmskog** [coq/opam-coq-archive#869]
One CI job for a recent [pull request](https://github.com/coq/opam-coq-archive/pull/868) mysteriously fails when installing the `coq.dev` package on OCaml 4.05.0, see [example job](https://gitlab.com/coq/opam-coq-archive/-/jobs/272549611). The job for 4.07.1 succeeds. Key error message:
```
# Error: failed to run ocaml
```
This might warrant some more investigation, e.g., we don't see the full `opam list` in the build log. One theory is that it might have something to do with `ocamlfind` (which seemingly is not explicitly installed).

**Comment by clarus** [comment]
Just got the same bug for this pull-request: https://github.com/coq/opam-coq-archive/pull/870

**Comment by clarus** [comment]
:+1: for having more logs during the builds. I do not know what changed recently.

**Comment by clarus** [comment]
I am closing this issue as it seems that the CI now runs without errors.
