### ISSUE TITLE
Coq RSA is not available for 8.9

### ISSUE THREAD

**Issue by spitters** [coq/opam-coq-archive#936]
Only for 8.8 and dev
https://github.com/coq/opam-coq-archive/tree/master/extra-dev/packages/coq-rsa

**Comment by clarus** [comment]
It seems that the `8.8` version actually works with Coq `8.9`. Temporal fix:
```
opam install coq-rsa.8.8.0 --ignore-deps
```
I do not know what is the policy for contribs, either to make a new tag `v8.9` identical to `v8.8` or say that the package `coq-rsa.8.8` is compatible with Coq `8.9`. I would be fine with the second option. Either way I think this is more an issue related to https://github.com/coq-contribs/rsa than the opam archive.

**Comment by clarus** [comment]
@spitters Just made a pull-request: https://github.com/coq/opam-coq-archive/pull/937

**Comment by clarus** [comment]
Fixed.
