### ISSUE TITLE
Coq-ext-lib dev does not install on 8.9

### ISSUE THREAD

**Issue by spitters** [coq/opam-coq-archive#939]
COQC theories/Structures/BinOps.v
 File "./theories/Structures/Applicative.v", line 20, characters 0-46:

coq-ext-lib.0.10.1 is working fine.

I previously mentioned this https://github.com/coq-community/manifesto/issues/15 , but this seems to be the appropriate place.

**Comment by Lysxia** [comment]
This should be fixed now (by coq-ext-lib/coq-ext-lib#71).

**Comment by clarus** [comment]
I confirm it can now install. From two days ago: https://coq-bench.github.io/clean/Linux-x86_64-4.07.1-2.0.1/extra-dev/8.9.dev/ext-lib/dev.html (though there may have been new breaking commits by now).

**Comment by clarus** [comment]
Thanks for the report.
