### ISSUE TITLE
coq-extra-dev opam repo is not up-to-date with opam-coq-archive

### ISSUE THREAD

**Issue by anton-trunov** [coq/opam-coq-archive#954]
This repo says:
https://github.com/coq/opam-coq-archive/blob/d50875618e8b5be475a7529c9bc9bbea0350325e/extra-dev/packages/coq-mathcomp-ssreflect/coq-mathcomp-ssreflect.dev/opam#L13 says

but `$ opam update; opam info coq-mathcomp-ssreflect` returns the following:
```
version      dev
repository   coq-extra-dev
...
depends:     "coq" {((>= "8.7" & < "8.10~") | (= "dev"))}
```

hence `$ opam install coq-mathcomp-ssreflect` fails on Coq 8.10.0:

```
The following dependencies couldn't be met:
  - coq-mathcomp-ssreflect → coq (< 8.10~ & = dev)
      no matching version
```

**Comment by clarus** [comment]
Ah, works on my machine. What does `opam repo` returns?

**Comment by anton-trunov** [comment]
```shell
$ opam repo
[NOTE] These are the repositories in use by the current switch. Use '--all' to see all configured repositories.

<><> Repository configuration for switch coq8.10 ><><><><><><><><><><><><><>  🐫
 1 coq-extra-dev https://coq.inria.fr/opam/extra-dev
 2 coq-released  https://coq.inria.fr/opam/released
 3 default       https://opam.ocaml.org
```

**Comment by clarus** [comment]
OK then I do not know.

**Comment by palmskog** [comment]
@anton-trunov I can't reproduce this, when I did:
```
opam update
opam info coq-mathcomp-ssreflect
```
I see the following line:
```
depends:     "coq" {(>= "8.7" & < "8.11~") | (= "dev")}
```
Do you have the latest `opam` (2.0.5)? Earlier versions had several bugs. If nothing else works, I would just do a new opam initialization (remove `.opam` and do `opam init`).

**Comment by anton-trunov** [comment]
Oh, I think I figured it out. The following script leads to that weird state.

```
opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
opam pin add coq-mathcomp-ssreflect --dev --no-action
opam install coq-mathcomp-ssreflect

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><>  🐫
[coq-mathcomp-ssreflect.dev] no changes from git+https://github.com/math-comp/math-comp.git

The following dependencies couldn't be met:
  - coq-mathcomp-ssreflect → coq (< 8.10~ & = dev)
      no matching version

No solution found, exiting
```

`opam info coq-mathcomp-ssreflect` says 
```
version      dev
repository   coq-extra-dev
pin          git+https://github.com/math-comp/math-comp.git
```
but in reality the `opam` file comes not from `coq-extra-dev`, but from `https://github.com/math-comp/math-comp#master`, which is not in sync with the opam repository.

This makes me wonder if `coq-extra-dev` is useful at all. Perhaps people should keep the development versions of their `opam` files directly in the corresponding repos, since `opam` can perfectly fetch the package info from there. This should solve the issue of synchronization, unless I'm missing something.

**Comment by anton-trunov** [comment]
@clarus , @palmskog That was helpful, thanks a lot!
