### ISSUE TITLE
CompCert compilation fails with all default dependencies

### ISSUE THREAD

**Issue by zoickx** [coq/opam-coq-archive#974]
Attempting to install [`coq-compcert`](https://github.com/coq/opam-coq-archive/tree/47216e2bb049f23ad3399699339b63290b84d70e/released/packages/coq-compcert) from a clean opam switch (with the latest compiler - `4.09.0`) successfully installs all dependencies, but the compilation of `coq-compcert` fails.

### Steps to reproduce
```bash
opam switch create bug-report 4.09.0
opam repo add coq-released https://coq.inria.fr/opam/released
opam update; opam upgrade # probably optional; added for good measure
opam install coq-compcert
```

### Expected result
CompCert installed

### Actual result
All CompCert's dependencies successfully installed, compilation of `coq-compcert` exits with an error:
```
[ERROR] The compilation of coq-compcert failed at "/home/zoickx/.opam/opam-init/hooks/sandbox.sh build make -j7".

#=== ERROR while compiling coq-compcert.3.5 ===================================#
# context     2.0.4 | linux/x86_64 | ocaml-base-compiler.4.09.0 | https://coq.inria.fr/opam/released#2019-10-23 00:30
# path        ~/.opam/bug-report/.opam-switch/build/coq-compcert.3.5
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j7
# exit-code   2
# env-file    ~/.opam/log/coq-compcert-10793-2e99e3.env
# output-file ~/.opam/log/coq-compcert-10793-2e99e3.out
### output ###
# [...]
# OCAMLC   extraction/Integers.mli
# OCAMLOPT extraction/Ordered.ml
# OCAMLOPT extraction/FSetAVL.ml
# OCAMLOPT extraction/Lattice.ml
# OCAMLC   extraction/Kildall.mli
# OCAMLOPT extraction/Unityping.ml
# make[2]: *** [Makefile.extr:123: cparser/Cutil.cmx] Error 2
# make[2]: *** Waiting for unfinished jobs....
# make[2]: Leaving directory '/home/zoickx/.opam/bug-report/.opam-switch/build/coq-compcert.3.5'
# make[1]: *** [Makefile:164: ccomp] Error 2
# make[1]: Leaving directory '/home/zoickx/.opam/bug-report/.opam-switch/build/coq-compcert.3.5'
# make: *** [Makefile:139: all] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build coq-compcert 3.5
└─
┌─ The following changes have been performed
│ ∗ install camlp5     7.10
│ ∗ install conf-m4    1
│ ∗ install coq        8.9.1
│ ∗ install menhir     20181113
│ ∗ install num        1.2
│ ∗ install ocamlbuild 0.14.0
│ ∗ install ocamlfind  1.8.1
└─
```
Log files: [logfiles.zip](https://github.com/coq/opam-coq-archive/files/3764400/logfiles.zip)

### Additional information
* Error and logs are from opam 2.0.4, installed through nix
* The same problem occurs with clean opam installed as described [here](https://opam.ocaml.org/doc/Install.html#Binary-distribution), initialized with `opam init`
* Tested on multiple machines and OSs: NixOS, Arch Linux, Ubuntu, Elementary OS. I believe the error messages differed, but unfortunately can not  provide any others than NixOS.
* I was unable to pin down the problem to any concrete combinations of package versions, but can report that using `ocaml-base-compiler 4.05.0` as the base of the switch solves the issue. The following succeeds on my machine:
```bash
opam switch create bug-report 4.09.0
opam repo add coq-released https://coq.inria.fr/opam/released
opam install coq-compcert
```

**Comment by zoickx** [comment]
@vzaliva

**Comment by clarus** [comment]
OK bad, extremely bad. Thanks for the detailed report! We are blind on the OCaml 4.09 version in CIs. Will fix that. @jhjourdan for the record, small bug in CompCert, fix under way.

**Comment by jhjourdan** [comment]
This is a known incompatibility between CompCert <= 3.5 and OCaml >= 4.08. This has been fixed recently:

https://github.com/AbsInt/CompCert/commit/96383f6dbccd4b280acad395b9a2683a645a9de3

**Comment by clarus** [comment]
Also, there are no opam packages for the latest version 3.6 of CompCert. I can add one.

**Comment by clarus** [comment]
@zoickx Do you confirm everything works as expected now?

**Comment by zoickx** [comment]
@clarus, yes, installing all defaults (i.e. Coq 8.10.1, CompCert 3.6) works as expected, although, of course, trying to install the original set of packages in the issue fails with a (now understandable) message about incompatibility between `coq-compcer t= 3.5` and `ocaml >= 3.8.0`.

Works for me, thanks!

**Comment by clarus** [comment]
Top!
