### ISSUE TITLE
Clarifying the purpose of the coq package?

### ISSUE THREAD

**Issue by herbelin** [coq/opam-coq-archive#99]
I wonder whether it is not disturbing that the "coq" package is in the list of coq packages at https://coq.inria.fr/opam/www/

Wouldn't it be clearer to remove core-dev from the list generated to build the index page?

I wonder what others think?

**Comment by matej-kosik** [comment]
I think that it makes sense to not list packages in `core-dev` directory.

**Comment by mattam82** [comment]
Hmm, why not? I mean some people install coq from opam so why not list it there?

**Comment by silene** [comment]
> I mean some people install coq from opam so why not list it there?

Because none of these versions are official, so it would be misleading. The official releases are in the primary opam repository, which this page does not track.

**Comment by mattam82** [comment]
Ok. But the betas are only there aren't they?

**Comment by mattam82** [comment]
I can easily fix the script to not add them for sure.

**Comment by maximedenes** [comment]
I just removed the coq package from the list again. Closing.

**Comment by herbelin** [comment]
OK. Thanks.
